# Generated by Django 6.0.5 on 2026-05-25 19:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_lucro_padrao', models.DecimalField(decimal_places=2, default=30.0, help_text='Margem de lucro global sugerida para novos produtos (%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(default=0, help_text='Quantidade total de unidades no estoque')),
                ('data_compra', models.DateTimeField(blank=True, null=True)),
                ('valor_adquirido', models.DecimalField(decimal_places=2, help_text='Valor total de custo gasto na aquisição desse lote', max_digits=10)),
                ('porcentagem_ganho', models.DecimalField(decimal_places=2, help_text='Porcentagem de ganho desejada sobre o custo unitário (%)', max_digits=5)),
                ('valor_venda_sugerido', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor de venda sugerido baseado na porcentagem de ganho', max_digits=10)),
                ('valor_venda_final', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor efetivo de venda praticado', max_digits=10)),
                ('eh_caixa', models.BooleanField(default=False, help_text='Indica se o produto foi comprado fechado em caixa de múltiplas unidades')),
                ('quantidade_por_caixa', models.IntegerField(blank=True, default=1, help_text='Se comprado em caixa, quantas unidades físicas vem dentro dela', null=True)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0.0, help_text='Custo de aquisição unitário calculado', max_digits=10)),
                ('ativo', models.BooleanField(default=True, help_text='Soft Delete: Define se o produto está ativo no sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('MEMBRO', 'Membro Operacional')], default='MEMBRO', help_text='Define o nível de acesso e perfil do usuário', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('nivel', models.CharField(choices=[('Information', 'Information'), ('Warning', 'Warning'), ('Error', 'Error')], default='Information', max_length=15)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='MembroPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_cadastrar_produto', models.BooleanField(default=False)),
                ('pode_editar_produto', models.BooleanField(default=False)),
                ('pode_excluir_produto', models.BooleanField(default=False)),
                ('pode_visualizar_dashboard', models.BooleanField(default=False)),
                ('pode_cadastrar_venda', models.BooleanField(default=False)),
                ('pode_alterar_porcentagem_lucro', models.BooleanField(default=False)),
                ('pode_gerenciar_membros', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_pessoa', models.CharField(help_text='Identificação de quem comprou ou retirou', max_length=255)),
                ('forma_pagamento', models.IntegerField(choices=[(1, 'Caixinha'), (2, 'Pix')], default=2)),
                ('valor_total_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lucro_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_vendida', models.IntegerField()),
                ('custo_unitario_historico', models.DecimalField(decimal_places=2, help_text='Custo unitário do produto na hora da venda para garantir integridade do lucro histórico', max_digits=10)),
                ('valor_unitario_venda', models.DecimalField(decimal_places=2, help_text='Preço final unitário de venda praticado neste item', max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, default=0.0, help_text='Lucro obtido nessa venda (Valor Venda - Custo Histórico) * Qtd', max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_itens', to='estoque.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.venda')),
            ],
        ),
    ]
