# Generated by Django 6.0.5 on 2026-05-25 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, help_text='Foto de perfil do usuário', null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
