# Generated by Django 6.0.5 on 2026-07-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_usuario_foto_alter_venda_usuario_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Chave de API do Gemini para habilitar o chatbot de IA', max_length=255, null=True),
        ),
    ]
